Vagrant.require_plugin('vagrant-digitalocean')

Vagrant.configure('2') do |config|

  config.vm.define "Osipov" do |config|
      config.vm.provider :digital_ocean do |provider, override|
        override.ssh.private_key_path = '/root/.ssh/id_rsa'
        override.vm.box = 'digital_ocean'
        override.vm.box_url = "https://github.com/devopsgroup-io/vagrant-digitalocean/raw/master/box/digital_ocean.box"
        override.nfs.functional = false
        provider.token = 'Your token'
        provider.image = 'ubuntu-18-04-x64'
        provider.region = 'nyc1'
        provider.size = '1gb'
        provider.ssh_key_name = 'osipov_key'
        provider.tags = ['devops', 'dan4ex_at_yandex_ru']
      end
   end
end
